### ISSUE TITLE
  java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found  what should i do?

### ISSUE THREAD

**Issue by iot-hunter** [zhu260824/face_mnn#2]
020-08-18 01:30:08.014 2686-2686/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-18 01:30:08.015 2686-2686/? E/Zygote: accessInfo : 1
2020-08-18 01:30:08.014 2686-2686/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-18 01:30:08.014 2686-2686/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-18 01:30:08.015 2686-2686/? E/Zygote: accessInfo : 1
2020-08-18 01:30:08.436 2686-2686/com.zl.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zl.demo, PID: 2686
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.zl.face.FaceDetector.<clinit>(FaceDetector.java:17)
        at com.zl.demo.MainActivity.activate(MainActivity.java:142)
        at com.zl.demo.MainActivity.onCreate(MainActivity.java:104)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by jing-zzz** [comment]
你好，这个问题怎么解决的

**Comment by tomguluson92** [comment]
在CMakeLists.txt里，将openmp后面都加上`-static-openmp`
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp -static-openmp")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fopenmp -static-openmp")
```
